apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: demo
  namespace: eck
spec:
  version: 8.3.3
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
---
