apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: demo
  namespace: eck
spec:
  version: 8.3.3
  count: 1
  elasticsearchRef:
    name: demo
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://demo-es-http.eck.svc:9200","https://demo-es-data"]
    xpack.fleet.agents.elasticsearch.hosts: ["https://demo-es-http.eck.svc:9200","https://demo-es-masters.eck.svc:9200","https://demo-es-data.eck.svc:9200"]
      xpack.fleet.agents.fleet_server.hosts: ["https://demo-fleet-server-agent-http.eck.svc:8220"]
    xpack.fleet.packages:
    - name: apm
      version: latest
    - name: system
      version: latest
    - name: elastic_agent
      version: latest
    - name: fleet_server
      version: latest
    - name: kubernetes
      # pinning this version as the next one introduced a kube-proxy host setting default that breaks this recipe,
      # see https://github.com/elastic/integrations/pull/1565 for more details
      version: 0.14.0
    xpack.fleet.agentPolicies:
    - name: Fleet Server on ECK policy
      id: eck-fleet-server
      namespace: eck
      monitoring_enabled:
      - logs
      - metrics
      is_default_fleet_server: true
      package_policies:
      - name: fleet_server-1
        id: fleet_server-1
        package:
          name: fleet_server
    - name: Elastic Agent on ECK policy
      id: eck-agent
      namespace: eck
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      is_default: true
      package_policies:
      - package:
          name: system
        name: system-1
      - package:
          name: kubernetes
        name: kubernetes-1
