apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx2
  template:
    metadata:
      labels:
        run: mynginx2
    spec:
      containers:
      - image: nginx
        name: mynginx2
        ports:
        - containerPort: 80
