apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: eck
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
spec:
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  type: LoadBalancer
