apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: eck
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  ownerReferences:
  - apiVersion: kibana.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Kibana
    name: kibana
spec:
  ports:
  - name: https
    protocol: TCP
    port: 5601
    targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  type: LoadBalancer
