apiVersion: v1
kind: Service
metadata:
  name: mysql-fc
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fc
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # runtimeClassName: fc      
      containers:
      - image: mysql:5.6
        name: mysql-fc
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: dblab528
        ports:
        - containerPort: 3306
          name: mysql-fc
        volumeMounts:
        - name: mysql-persistent-storage-fc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-fc
        persistentVolumeClaim:
          claimName: mysql-pv-claim-fc
