apiVersion: v1
kind: Service
metadata:
  name: mysql-gvisor
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gvisor
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # runtimeClassName: gvisor
      containers:
      - image: mysql:5.6
        name: mysql-gvisor
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "300m"
            memory: "300Mi"
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: dblab528
        ports:
        - containerPort: 3306
          name: mysql-gvisor
        volumeMounts:
        - name: mysql-persistent-storage-gvisor
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-gvisor
        persistentVolumeClaim:
          claimName: mysql-pv-claim-gvisor
